name: Lint
on: push
jobs:
  release:
    name: Run eslint against the extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn run lint