name: Release
on:
  release:
    types: [created]
jobs:
  release:
    name: Zip up Chrome extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: background.js birthday.js icon128.png icon16.png icon48.png manifest.json README.md LICENSE.md
          dest: extension.zip
      - name: Publish artifacts on Github
        uses: softprops/action-gh-release@v1
        with:
          files: extension.zip
