name: Release
on:
  release:
    types: [created]
jobs:
  release:
    name: Zip up Chrome extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn run package
      - name: Publish artifacts on Github
        uses: softprops/action-gh-release@v1
        with:
          files: extension.zip
